name: Pipeline PROD

on:
  pull_request:
    branches: [ "PROD" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compilar o Projeto
      run: |
          cd src
          javac -cp . src/test/java/com/example/projeto_interdisciplinar
    - name: Executado Projeto 
      run: |
          cd src
          java -cp . src/test/java/com/example/projeto_interdisciplinar
    - uses: mr-smithers-excellent/docker-build-push@v6    
      name: Deploy no Docker 
      with:
        image: viniciustech/teeste
        tags: prod-1.${{ github.run_number }}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
